
set(SRC
    ${SRC}
    ${FreeRTOS_dir}/FreeRTOS_Kernel/list.c
    ${FreeRTOS_dir}/FreeRTOS_Kernel/queue.c
    ${FreeRTOS_dir}/FreeRTOS_Kernel/tasks.c 
    ${FreeRTOS_Kernel_dir}/portable/GCC/Posix/port.c 
    ${FreeRTOS_Kernel_dir}/portable/MemMang/heap_3.c 
    #${FreeRTOS_dir}/FreeRTOS_Kernel/croutine.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/GenQTest.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/QPeek.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/blocktim.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/countsem.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/crflash.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/crhook.c
    #${FreeRTOS_dir}/Common_Demo/Minimal/recmutex.c 
    #${FreeRTOS_dir}/Common_Demo/Full/BlockQ.c
    #${FreeRTOS_dir}/Common_Demo/Full/PollQ.c
    #${FreeRTOS_dir}/Common_Demo/Full/death.c
    #${FreeRTOS_dir}/Common_Demo/Full/dynamic.c
    #${FreeRTOS_dir}/Common_Demo/Full/events.c
    #${FreeRTOS_dir}/Common_Demo/Full/flash.c
    #${FreeRTOS_dir}/Common_Demo/Full/flop.c
    #${FreeRTOS_dir}/Common_Demo/Full/integer.c
    #${FreeRTOS_dir}/Common_Demo/Full/print.c
    #${FreeRTOS_dir}/Common_Demo/Full/semtest.c 
    #${FreeRTOS_dir}/ParTest/ParTest.c
    #${FreeRTOS_dir}/AsyncIO/AsyncIOSocket.c
    #${FreeRTOS_dir}/AsyncIO/PosixMessageQueueIPC.c 
    #${FreeRTOS_dir}/FileIO/fileIO.c 
)
