
set(MQTT_SRC
    ${evrythng-lib}/mqtt/src/Clients.c
    ${evrythng-lib}/mqtt/src/Heap.c
    #${evrythng-lib}/mqtt/src/Log.c
    ${evrythng-lib}/mqtt/src/LinkedList.c
    ${evrythng-lib}/mqtt/src/Messages.c
    ${evrythng-lib}/mqtt/src/MQTTClient.c
    ${evrythng-lib}/mqtt/src/MQTTPacket.c
    ${evrythng-lib}/mqtt/src/MQTTPacketOut.c
    ${evrythng-lib}/mqtt/src/MQTTProtocolClient.c
    ${evrythng-lib}/mqtt/src/MQTTProtocolOut.c
    ${evrythng-lib}/mqtt/src/SSLSocket.c
    ${evrythng-lib}/mqtt/src/TLSSocket.c
    ${evrythng-lib}/mqtt/src/Socket.c
    ${evrythng-lib}/mqtt/src/SocketBuffer.c
    ${evrythng-lib}/mqtt/src/Thread.c
    ${evrythng-lib}/mqtt/src/Tree.c
    ${evrythng-lib}/mqtt/src/utf-8.c
)
